resource_manager/accounting/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('operations/', operations, name='operations'),

    #receipts
    path('receipts/', receipts, name='receipts'),
    path('receipts/<str:receipt_type>/<int:receipt_id>/', receipt_detail, name='receipt_detail'),
    path('receipts/cheque/create/', create_cheque_receipt, name='create_cheque_receipt'),

    #Budgeting
    path('vote_head_budget/', vote_head_budget, name='vote_head_budget'),
    path('budgets/<int:budget_id>/', budget_detail, name='budget_detail'),
    path('create_budget/', create_votehead_budget, name='create_budget'),

    #PettyCash
    path('pettycash/', pettycash_list, name='pettycash_list'),
    path('pettycash/<int:pk>/', pettycash_detail, name='pettycash_detail'),
    path('pettycash/create/', create_pettycash, name='create_pettycash'),

    #PaymentVoucher
    path('payment-vouchers/', payment_voucher_list, name='payment_voucher_list'),
    path('paymentvoucher/<int:pk>/', paymentvoucher_detail, name='paymentvoucher_detail'),
    path('paymentvoucher/create/', create_paymentvoucher, name='create_paymentvoucher'),

    #cheque
    path('cheques/', cheque_list, name='cheque_list'),
    path('cheques/<int:cheque_id>/', cheque_detail, name='cheque_detail'),
    path('cheques/create/', create_cheque, name='create_cheque'),

    #cashbook
    path('cashbook/', cashbook, name='cashbook'),

    #My url
    path('my-url/', my_view, name='my_view'),


]

resource_manager/resource_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounting.urls'))
]

resource_manager/accounting/models.py
from django.db import models
from django.db.models import Sum
from django.db.models.signals import post_save
from django.dispatch import receiver, Signal



# Create your models here.

class OperationsCashAccount(models.Model):
    account_number = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=50)
    cash_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return self.name


class OperationsBankAccount(models.Model):
    account_number = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=50)
    bank_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    month_end_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return self.name


class OperationsCashReceipt(models.Model):
    account = models.ForeignKey(OperationsCashAccount, on_delete=models.CASCADE, default=None)
    received_from = models.CharField(max_length=100, default='')
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    date_received = models.DateField()

    def __str__(self):
        return f"Receipt {self.id} for {self.account.account_number} (Cash)"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        account = self.account
        amount = self.amount

        account.cash_balance += amount
        account.total_balance = account.cash_balance
        account.save()


class OperationsChequeReceipt(models.Model):
    account = models.ForeignKey(OperationsBankAccount, on_delete=models.CASCADE, default=None)
    received_from = models.CharField(max_length=100, default='')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date_received = models.DateField()

    def __str__(self):
        return f"Receipt {self.id} for {self.account.account_number} (Cheque)"


class PettyCash(models.Model):
    payee_name = models.CharField(max_length=100, default='')
    cheque_number = models.CharField(max_length=20, unique=True, default='')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date_issued = models.DateField()
    operations_account = models.ForeignKey(OperationsCashAccount, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return f"Petty Cash - {self.amount} ({self.date_issued}) - Payee: {self.payee_name}"


class VoteHead(models.Model):
    ACCOUNT_TYPES = (
        ('operations', 'Operations Account'),
        ('other', 'Other Account'),
    )

    name = models.CharField(max_length=100)
    account_type = models.CharField(max_length=20, choices=ACCOUNT_TYPES, default='other')
    account_number = models.CharField(max_length=20, unique=True, default='')
    account = models.ForeignKey(OperationsBankAccount, on_delete=models.CASCADE, default=None)
    amount_budgeted = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    amount_spent = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)


    def __str__(self):
        return self.name




class OperationsBudget(models.Model):
    account = models.ForeignKey(OperationsBankAccount, on_delete=models.CASCADE)
    cheque_receipt = models.ForeignKey(OperationsChequeReceipt, on_delete=models.CASCADE, default=None)
    votehead = models.ForeignKey(VoteHead, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date_budgeted = models.DateField()

    def __str__(self):
        return f"{self.votehead} budgeted {self.amount} for {self.account.account_number}"



class VoteHeadReceipt(models.Model):
    votehead = models.ForeignKey(VoteHead, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date_received = models.DateField()

    def __str__(self):
        return f"Receipt for {self.votehead} ({self.amount})"


class PaymentVoucher(models.Model):
    PAYMENT_TYPES = (
        ('cash', 'Cash'),
        ('cheque', 'Cheque'),
    )

    date = models.DateField()
    payee_name = models.CharField(max_length=100, default='')
    description = models.CharField(max_length=200)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_type = models.CharField(max_length=20, choices=PAYMENT_TYPES, default='cash')
    votehead = models.ForeignKey(VoteHead, on_delete=models.CASCADE)
    approved_by = models.CharField(max_length=100)
    voucher_number = models.CharField(max_length=20, unique=True, default='')
    cheque_number = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return f"{self.description} ({self.amount})"



class Cheque(models.Model):
    payee_name = models.CharField(max_length=100)
    cheque_number = models.CharField(max_length=20, unique=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date_issued = models.DateField()
    votehead = models.ForeignKey(VoteHead, on_delete=models.CASCADE, related_name='cheques', blank=True, null=True)
    remarks = models.TextField(blank=True)

    def __str__(self):
        return f'Cheque {self.cheque_number} issued to {self.payee_name} on {self.date_issued}'

resource_manager/accounting/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import *
from .budget_utils import update_voteheadreceipts
from datetime import datetime, timedelta



# Create your views here.

def home(request):
    return render(request, 'accounting/home.html')


# The DashBoard
def dashboard(request):
    return render(request, 'accounting/dashboard.html')


#Operations
def operations(request):
    return render(request, 'accounting/operations.html')


#Receipts
def receipts(request):
    cash_receipts = OperationsCashReceipt.objects.all()
    bank_receipts = OperationsChequeReceipt.objects.all()

    context = {
        'cash_receipts': cash_receipts,
        'bank_receipts': bank_receipts,
    }

    return render(request, 'accounting/receipts.html', context)


# Receipt Detail
def receipt_detail(request, receipt_type, receipt_id):
    if receipt_type == 'cash':
        receipt = OperationsCashReceipt.objects.filter(id=receipt_id).first()
        template = 'accounting/cash_receipt_detail.html'
    elif receipt_type == 'cheque':
        receipt = OperationsChequeReceipt.objects.filter(id=receipt_id).first()
        template = 'accounting/cheque_receipt_detail.html'
    else:
        raise Http404("Receipt type does not exist")
    
    if not receipt:
        raise Http404("Receipt does not exist")
    
    context = {
        'receipt': receipt,
        'receipt_type': receipt_type.capitalize() + ' Receipt',
    }
    
    return render(request, template, context)


# Create Cheque Receipt
def create_cheque_receipt(request):
    form = ChequeReceiptForm(request.POST or None)
    if form.is_valid():
        cheque_receipt = form.save()
        return redirect('receipt_detail', receipt_type='cheque', receipt_id=cheque_receipt.id)

    context = {
        'form': form,
    }
    return render(request, 'accounting/create_cheque_receipt.html', context)


#Budgeting
def vote_head_budget(request):
    budgets = OperationsBudget.objects.all()
    context = {
        'budgets': budgets
    }
    return render(request, 'accounting/vote_head_budget.html', context)


#Budget Detail
def budget_detail(request, budget_id):
    budget = get_object_or_404(OperationsBudget, id=budget_id)
    context = {
        'budget': budget,
    }
    return render(request, 'accounting/budget_detail.html', context)


#Create budget view
def create_votehead_budget(request):
    if request.method == 'POST':
        form = OperationsBudgetForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('vote_head_budget')
    else:
        form = OperationsBudgetForm()
    context = {'form': form}
    return render(request, 'accounting/create_votehead_budget.html', context)


#PettyCash
def pettycash_list(request):
    pettycash = PettyCash.objects.all()
    context = {'pettycash': pettycash}
    return render(request, 'accounting/pettycash_list.html', context)


#PettyCashDetail
def pettycash_detail(request, pk):
    pettycash = get_object_or_404(PettyCash, pk=pk)
    context = {'pettycash': pettycash}
    return render(request, 'accounting/pettycash_detail.html', context)


#Create PettyCash
def create_pettycash(request):
    if request.method == 'POST':
        form = PettyCashForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pettycash_list')
    else:
        form = PettyCashForm()
    context = {'form': form}
    return render(request, 'accounting/create_pettycash.html', context)


#PaymentVoucher
def payment_voucher_list(request):
    vouchers = PaymentVoucher.objects.all()
    context = {'vouchers': vouchers}
    return render(request, 'accounting/payment_voucher_list.html', context)


#PaymentVoucher Detail
def paymentvoucher_detail(request, pk):
    paymentvoucher = get_object_or_404(PaymentVoucher, pk=pk)
    context = {'paymentvoucher': paymentvoucher}
    return render(request, 'accounting/paymentvoucher_detail.html', context)


#Create PaymentVoucher
def create_paymentvoucher(request):
    if request.method == 'POST':
        form = PaymentVoucherForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('payment_voucher_list')
    else:
        form = PaymentVoucherForm()
    context = {'form': form}
    return render(request, 'accounting/create_paymentvoucher.html', context)


#The cheques
def cheque_list(request):
    cheques = Cheque.objects.all()
    context = {'cheques': cheques}
    return render(request, 'accounting/cheque_list.html', context)


#The cheque detail
def cheque_detail(request, cheque_id):
    cheque = get_object_or_404(Cheque, id=cheque_id)
    context = {
        'cheque': cheque,
    }
    return render(request, 'accounting/cheque_detail.html', context)


# The create cheque view
def create_cheque(request):
    if request.method == 'POST':
        form = ChequeForm(request.POST)
        if form.is_valid():
            cheque = form.save()
            return redirect('cheque_detail', cheque_id=cheque.pk)
    else:
        form = ChequeForm()
    context = {
        'form': form,
    }
    return render(request, 'accounting/create_cheque.html', context)


#The Cashbook
def cashbook(request):
    # Get the latest cheque receipt
    try:
        latest_receipt = OperationsChequeReceipt.objects.latest('date_received')
    except OperationsChequeReceipt.DoesNotExist:
        latest_receipt = None

    # Get all the cash receipts
    cash_receipts = OperationsCashReceipt.objects.all()

    # Get all the votehead objects
    voteheads = VoteHead.objects.all()

    # Get all the payment vouchers with cash as the payment type
    payment_vouchers = PaymentVoucher.objects.all()

    # Get all the budget objects
    budgets = OperationsBudget.objects.all()

    context = {
        'latest_receipt': latest_receipt,
        'voteheads': voteheads,
        'checkreceipts': OperationsChequeReceipt.objects.all(),
        'payment_vouchers': payment_vouchers,
        'cashreceipts': cash_receipts,
        'budgets': budgets
    }

    return render(request, 'accounting/cashbook.html', context)




#What I need
def my_view(request):
    # Get the current date
    current_date = datetime.now()

    # Calculate the previous month and year
    previous_date = current_date - timedelta(days=current_date.day)
    previous_month = previous_date.month
    previous_year = previous_date.year

    # Check if the votehead budgets for the previous month and year exist and are not zero
    votehead_budgets_exist = OperationsBudget.objects.filter(date_budgeted__year=previous_year, date_budgeted__month=previous_month).exists()
    votehead_budgets_not_zero = OperationsBudget.objects.filter(date_budgeted__year=previous_year, date_budgeted__month=previous_month, amount__gt=0).exists()

    # Update the votehead budgets for the previous month and year if they don't exist or are zero
    if not (votehead_budgets_exist and votehead_budgets_not_zero):
        update_voteheadreceipts(previous_month, previous_year)

    # Get all the cheque receipts for the previous month and year
    cheque_receipts = OperationsChequeReceipt.objects.filter(date_received__year=previous_year, date_received__month=previous_month)

    # Get the votehead budgets for the previous month and year
    votehead_budgets = OperationsBudget.objects.filter(date_budgeted__year=previous_year, date_budgeted__month=previous_month)

    # Pass the cheque_receipts and votehead_budgets to the template
    context = {
        'cheque_receipts': cheque_receipts,
        'votehead_budgets': votehead_budgets
    }
    return render(request, 'accounting/my_template.html', context)

resource_manager/accounting/templates/accounting/budget_detail.html
<h1>Budget Detail</h1>
<style>
    th {
    padding: 10px 20px;
    }
    td {
        padding: 10px 20px;
    }
</style>
<table>
  <tbody>
    <tr>
      <th>Account Number:</th>
      <td>{{ budget.account.account_number }}</td>
    </tr>
    <tr>
      <th>Votehead:</th>
      <td>{{ budget.votehead.name }}</td>
    </tr>
    <tr>
      <th>Amount Budgeted:</th>
      <td>{{ budget.amount }}</td>
    </tr>
    <tr>
      <th>Date Budgeted:</th>
      <td>{{ budget.date_budgeted }}</td>
    </tr>
  </tbody>
</table>

resource_manager/accounting/templates/accounting/cash_receipt_detail.html
{% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
        <title>My Accounting Software Dashboard</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/receipt_detail.css' %}">
    </head>
    <body>
        <div class="container">
            <div class="sidebar">
                <div class="top-section">
                    <div class="menu-control">
                        <span class="material-icons-sharp" id="menu-icon">menu</span>
                        <span class="material-icons-sharp" id="close-icon">close</span>
                    </div>
                    <div class="sidebar-header">
                        <h3>Accounts</h3>
                    </div>
                </div>
                <ul class="sidebar-menu">
                    <li>
                        <span class="material-icons-sharp">space_dashboard</span>
                        <a href="Operations/operations.html">Operations</a>
                    </li>
                    <li>
                        <span class="material-icons-sharp">space_dashboard</span>
                        <a href="#">Tuition</a>
                    </li>
                    <li>
                        <span class="material-icons-sharp">space_dashboard</span>
                        <a href="#">School Fund</a>
                    </li>
                </ul>
            </div>        
            <div class="main-content">
                <div class="main-top">
                    <h1>Receipt Details</h1>
                    <ul class="operation-links">
                        <li>
                            <a href="#">OtherDocs</a>
                        </li>
                        <li>
                            <a href="#">Cashbooks</a>
                        </li>
                        <li>
                            <a href="#">Ledgers</a>
                        </li>
                        <li>
                            <a href="#">TrialBalances</a>
                        </li>
                    </ul>
                </div>
                <div class="main-bottom">
                    <div class="receipt-list">
                        <a href="#" class="back-button">&larr; Back</a>
                        <div class="receipt-row">
                            <div class="receipt-detail-header">
                              <div class="receipt-col">
                                <div class="label">Account:</div>
                                <div class="value">{{ receipt.account }}</div>
                              </div>
                              <div class="receipt-col">
                                <div class="label">Received From:</div>
                                <div class="value">{{ receipt.received_from }}</div>
                              </div>
                              <div class="receipt-col">
                                <div class="label">Amount:</div>
                                <div class="value">{{ receipt.amount }}</div>
                              </div>
                              <div class="receipt-col">
                                <div class="label">Date Received:</div>
                                <div class="value">{{ receipt.date_received }}</div>
                              </div>
                            </div>
                          </div> 
                          
                          <div class="action-button">
                            <button class="update-button">Update</button>
                            <button class="delete-button">Delete</button>
                        </div>
                    </div>
                </div>
                </div>
                     
            </div>
        </div>    
    </body>
    </html>
    <script src="{% static 'js/receipt_detail.js' %}"></script>

resource_manager/accounting/templates/accounting/cheque_receipt_detail.html
{% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
        <title>My Accounting Software Dashboard</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/receipt_detail.css' %}">
    </head>
    <body>
        <div class="container">
            <div class="sidebar">
                <div class="top-section">
                    <div class="menu-control">
                        <span class="material-icons-sharp" id="menu-icon">menu</span>
                        <span class="material-icons-sharp" id="close-icon">close</span>
                    </div>
                    <div class="sidebar-header">
                        <h3>Accounts</h3>
                    </div>
                </div>
                <ul class="sidebar-menu">
                    <li>
                        <span class="material-icons-sharp">space_dashboard</span>
                        <a href="Operations/operations.html">Operations</a>
                    </li>
                    <li>
                        <span class="material-icons-sharp">space_dashboard</span>
                        <a href="#">Tuition</a>
                    </li>
                    <li>
                        <span class="material-icons-sharp">space_dashboard</span>
                        <a href="#">School Fund</a>
                    </li>
                </ul>
            </div>        
            <div class="main-content">
                <div class="main-top">
                    <h1>Receipt Details</h1>
                    <ul class="operation-links">
                        <li>
                            <a href="#">OtherDocs</a>
                        </li>
                        <li>
                            <a href="#">Cashbooks</a>
                        </li>
                        <li>
                            <a href="#">Ledgers</a>
                        </li>
                        <li>
                            <a href="#">TrialBalances</a>
                        </li>
                    </ul>
                </div>
                <div class="main-bottom">
                    <div class="receipt-list">
                        <a href="#" class="back-button">&larr; Back</a>
                        <div class="receipt-row">
                            <div class="receipt-detail-header">
                              <div class="receipt-col">
                                <div class="label">Account:</div>
                                <div class="value">{{ receipt.account }}</div>
                              </div>
                              <div class="receipt-col">
                                <div class="label">Received From:</div>
                                <div class="value">{{ receipt.received_from }}</div>
                              </div>
                              <div class="receipt-col">
                                <div class="label">Amount:</div>
                                <div class="value">{{ receipt.amount }}</div>
                              </div>
                              <div class="receipt-col">
                                <div class="label">Date Received:</div>
                                <div class="value">{{ receipt.date_received }}</div>
                              </div>
                            </div>
                          </div> 
                          
                          <div class="action-button">
                            <button class="update-button">Update</button>
                            <button class="delete-button">Delete</button>
                        </div>
                    </div>
                </div>
                </div>
                     
            </div>
        </div>    
    </body>
    </html>
    <script src="{% static 'js/receipt_detail.js' %}"></script>

resource_manager/accounting/templates/accounting/create_votehead_budget.html
<h1>Create Vote Head Budget</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>

resource_manager/accounting/templates/accounting/dashboard.html
<!-- dashboard.html -->
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
  </head>
  <body>
    <h1>Welcome to your dashboard!</h1>
    <p>Here are some links to help you get started:</p>
    <ul>
      <li><a href="{% url 'operations' %}">Operations Account</a></li>
    </ul>
  </body>
</html>

resource_manager/accounting/templates/accounting/my_template.html
<h1>Cheque Receipts and Votehead Budgets</h1>

{% if cheque_receipts %}
  <h2>Cheque Receipts:</h2>
  <ul>
  {% for receipt in cheque_receipts %}
    <li>{{ receipt.date_received }} - {{ receipt.amount }}</li>
  {% endfor %}
  </ul>
{% else %}
  <p>No cheque receipts found for the selected month and year.</p>
{% endif %}

{% if votehead_budgets %}
  <h2>Votehead Budgets:</h2>
  <ul>
  {% for budget in votehead_budgets %}
    <li>{{ budget.votehead }} - {{ budget.amount }}</li>
  {% endfor %}
  </ul>
{% else %}
  <p>No votehead budgets found for the selected month and year.</p>
{% endif %}

resource_manager/accounting/templates/accounting/payment_voucher_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
    <title>My Accounting Software Dashboard</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/payment_voucher_list.css' %}">
</head>
<body>
    <div class="container">
        <div class="sidebar">
            <div class="top-section">
                <div class="menu-control">
                    <span class="material-icons-sharp" id="menu-icon">menu</span>
                    <span class="material-icons-sharp" id="close-icon">close</span>
                </div>
                <div class="sidebar-header">
                    <h3>Accounts</h3>
                </div>
            </div>
            <ul class="sidebar-menu">
                <li>
                    <span class="material-icons-sharp">space_dashboard</span>
                    <a href="Operations/operations.html">Operations</a>
                </li>
                <li>
                    <span class="material-icons-sharp">space_dashboard</span>
                    <a href="#">Tuition</a>
                </li>
                <li>
                    <span class="material-icons-sharp">space_dashboard</span>
                    <a href="#">School Fund</a>
                </li>
            </ul>
        </div>        
        <div class="main-content">
            <div class="main-top">
                <h1>Payment Vouchers</h1>
                <ul class="operation-links">
                    <li>
                        <a href="#">OtherDocs</a>
                    </li>
                    <li>
                        <a href="#">Cashbooks</a>
                    </li>
                    <li>
                        <a href="#">Ledgers</a>
                    </li>
                    <li>
                        <a href="#">TrialBalances</a>
                    </li>
                </ul>
            </div>
            <div class="main-bottom">
                <a href="#" class="create-receipt-button">Create</a>
                <div class="receipt-list">
                    <div class="receipt-header">
                        <div class="receipt-col"><span>Voucher Number</span></div>
                        <div class="receipt-col"><span>Date</span></div>
                        <div class="receipt-col"><span>Payee</span></div>
                        <div class="receipt-col"><span>Amount</span></div>
                        <div class="receipt-col"><span>Type</span></div>
                        <div class="receipt-col"><span>Action</span></div>
                    </div>
                    {% for voucher in vouchers %}
                    <div class="receipt-row">
                        <div class="receipt-header-responsive">
                            <div class="receipt-col"><span>Voucher Number</span></div>
                            <div class="receipt-col"><span>Date</span></div>
                            <div class="receipt-col"><span>Payee</span></div>
                            <div class="receipt-col"><span>Amount</span></div>
                            <div class="receipt-col"><span>Type</span></div>
                            <div class="receipt-col"><span>Action</span></div>
                        </div>
                        <div class="receipt-row-col">
                            <div class="receipt-col"><span>{{ voucher.voucher_number }}</span></div>
                            <div class="receipt-col"><span>{{ voucher.date }}</span></div>
                            <div class="receipt-col"><span>{{ voucher.payee_name }}</span></div>
                            <div class="receipt-col"><span>{{ voucher.amount }}</span></div>
                            <div class="receipt-col"><span>{{ voucher.get_payment_type_display }}</span></div>
                            <div class="receipt-col"><button>
                              <a href="{% url 'paymentvoucher_detail' voucher.id %}">Details</a>
                            </button></div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
                 
        </div>
    </div>    
</body>
</html>
<script src="{% static 'js/payment_voucher_list.js' %}"></script>

resource_manager/accounting/templates/accounting/vote_head_budget.html
<h1>Vote Head Budget</h1>
<a href="{% url 'create_budget' %}">Create Budget</a>
<style>
    th {
    padding: 10px 20px;
    }
    td {
        padding: 10px 20px;
    }
</style>
<table>
  <thead>
    <tr>
      <th>Account Number</th>
      <th>Votehead</th>
      <th>Amount Budgeted</th>
      <th>Date Budgeted</th>
      <th>Detail</th>
    </tr>
  </thead>
  <tbody>
    {% for budget in budgets %}
    <tr>
      <td>{{ budget.account.account_number }}</td>
      <td>{{ budget.votehead.name }}</td>
      <td>{{ budget.amount }}</td>
      <td>{{ budget.date_budgeted }}</td>
      <td><a href="{% url 'budget_detail' budget_id=budget.id %}">Details</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>